---
- name: Install and configure Apache2
  hosts: all
  become: yes
  tasks:
    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Ensure Apache2 is running
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Allow Apache2 through the firewall
      ufw:
        rule: allow
        port: '80'
        proto: tcp

    - name: Create index.html file
      copy:
        content: "<html><body><h1>Welcome to Apache2!</h1></body></html>"
        dest: /var/www/html/index.html
