---
- name: Deploy Docker Compose services
  hosts: all
  become: yes
  tasks:
    - name: Copy Docker Compose file to the host
      copy:
        src: /home/adc/docker-compose/inventory_management/docker-compose.yml
        dest: /home/vagrant/compose/docker-compose.yml

    - name: Ensure required ports are open
      become: yes
      ansible.builtin.ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:
        - 3000
        - 8000
        - 5432

    - name: Start Docker Compose services
      command: docker-compose -f /home/vagrant/compose/docker-compose.yml up -d
