---
- name: Install Docker and Docker Compose
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install packages required for Docker
      package:
        name: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common']
      when: ansible_os_family == 'Debian'

    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
      when: ansible_os_family == 'Debian'

    - name: Add Docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
      when: ansible_os_family == 'Debian'

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install Python pip (required for Docker Compose installation)
      apt:
        name: python3-pip
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install necessary development packages
      apt:
        name: ['build-essential', 'libssl-dev', 'libffi-dev', 'python3-dev']
      when: ansible_os_family == 'Debian'

    - name: Install setuptools-rust
      pip:
        name: setuptools-rust
        state: present
      when: ansible_os_family == 'Debian'

    - name: Retry installing Docker Compose
      pip:
        name: docker-compose
        state: present
      when: ansible_os_family == 'Debian'

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes
      when: ansible_os_family == 'Debian'
